package com.million.common;

public interface Constants {
	
	String FIELD_NAME_SCRIP_NAME = "SCRIP_NAME";
	
	String FIELD_NAME_ENTRY_PRICE_LEVEL = "ENTRY_PRICE_LEVEL";
	
	String FIELD_NAME_OTA_TRADE_TYPE = "OTA_TRADE_TYPE";
	
	String FIELD_NAME_QUANTITY = "QUANTITY";
	
	String COMMA_SEPERATOR = ",";

	String CACHE_GROUP_LOG_MESSAGES = "CACHE_GROUP_LOG_MESSAGES";

	String WRITE_IN_CSV = "WriteInCSV";

	String CACHE_GROUP_INTRADAY_ORDERS = "CACHE_GROUP_INTRADAY_ORDERS";

	String FIELD_NAME_TRADE_TYPE = "TRADE_TYPE";

	String FIELD_NAME_SL_PRICE = "SL_PRICE";

	String FIELD_NAME_DATR = "DATR";

	String ACTION_TYPE_SELL = "SELL";

	String INTRADAY_MAX_LOSS = "INTRADAY_MAX_LOSS";

	String FIELD_NAME_EXCHANGE = "EXCHANGE";

	String ACTION_TYPE_BUY = "BUY";
	

}
